CONFIG_SPI=y
CONFIG_GPIO_595=y

# Uncomment to enable encoder
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Reduce firmware size
CONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=n
CONFIG_ZMK_BATTERY_REPORTING=n
CONFIG_USB_DEVICE_MANUFACTURER="ZMK"


CONFIG_ZMK_DISPLAY=y
CONFIG_DISPLAY=y
CONFIG_SSD1306=y
CONFIG_I2C=y
CONFIG_LV_Z_MEM_POOL_SIZE=2048
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y

CONFIG_I2C_LOG_LEVEL_DBG=y
CONFIG_SSD1306_LOG_LEVEL_DBG=y